name: MemoryDependentComputation

channels:
    - pytorch
    - defaults
    - conda-forge

dependencies:
    - pytorch::pytorch=1.7.0
    - pytorch::torchaudio=0.7.0
    - pytorch::torchvision=0.8.1
    - defaults::cudatoolkit=10.2.89
    - defaults::tensorboard=2.3.0
    - defaults::matplotlib=3.3.2
    - conda-forge::scikit-learn=1.0.2
    - conda-forge::gym=0.18.0
    - conda-forge::tqdm=4.59.0
    - conda-forge::stable-baselines3=1.1.0